export const GET_ADDRESS_PENDING = 'GET_ADDRESS_PENDING';
export const GET_ADDRESS_FULFILLED = 'GET_ADDRESS_FULFILLED';
export const GET_ADDRESS_REJECTED = 'GET_ADDRESS_REJECTED';

export const ADD_ADDRESS_PENDING = 'ADD_ADDRESS_PENDING';
export const ADD_ADDRESS_FULFILLED = 'ADD_ADDRESS_FULFILLED';
export const ADD_ADDRESS_REJECTED = 'ADD_ADDRESS_REJECTED';

export const UPDATE_ADDRESS_PENDING = 'UPDATE_ADDRESS_PENDING';
export const UPDATE_ADDRESS_FULFILLED = 'UPDATE_ADDRESS_FULFILLED';
export const UPDATE_ADDRESS_REJECTED = 'UPDATE_ADDRESS_REJECTED';

export const DELETE_ADDRESS_PENDING = 'DELETE_ADDRESS_PENDING';
export const DELETE_ADDRESS_FULFILLED = 'DELETE_ADDRESS_FULFILLED';
export const DELETE_ADDRESS_REJECTED = 'DELETE_ADDRESS_REJECTED';

export const SET_SELECTED_ADDRESS = 'SET_SELECTED_ADDRESS';
export const CLEAR_SELECTED_ADDRESS = 'CLEAR_SELECTED_ADDRESS';