export const SET_ORDER_DATA = 'SET_ORDER_DATA';

export const CREATE_ORDER_PENDING = 'CREATE_ORDER_PENDING';
export const CREATE_ORDER_FULFILLED = 'CREATE_ORDER_FULFILLED';
export const CREATE_ORDER_REJECTED = 'CREATE_ORDER_REJECTED';

export const GET_ORDER_PENDING = 'GET_ORDER_PENDING';
export const GET_ORDER_FULFILLED = 'GET_ORDER_FULFILLED';
export const GET_ORDER_REJECTED = 'GET_ORDER_REJECTED';

export const GET_USER_ORDERS_PENDING = 'GET_USER_ORDERS_PENDING';
export const GET_USER_ORDERS_FULFILLED = 'GET_USER_ORDERS_FULFILLED';
export const GET_USER_ORDERS_REJECTED = 'GET_USER_ORDERS_REJECTED';

export const PROCESS_PAYMENT_PENDING = 'PROCESS_PAYMENT_PENDING';
export const PROCESS_PAYMENT_FULFILLED = 'PROCESS_PAYMENT_FULFILLED';
export const PROCESS_PAYMENT_REJECTED = 'PROCESS_PAYMENT_REJECTED';

export const VERIFY_PAYMENT_PENDING = 'VERIFY_PAYMENT_PENDING';
export const VERIFY_PAYMENT_FULFILLED = 'VERIFY_PAYMENT_FULFILLED';
export const VERIFY_PAYMENT_REJECTED = 'VERIFY_PAYMENT_REJECTED';

export const CANCEL_ORDER_PENDING = 'CANCEL_ORDER_PENDING';
export const CANCEL_ORDER_FULFILLED = 'CANCEL_ORDER_FULFILLED';
export const CANCEL_ORDER_REJECTED = 'CANCEL_ORDER_REJECTED';