export const GET_PROFILE_PENDING = 'GET_PROFILE_PENDING';
export const GET_PROFILE_FULFILLED = 'GET_PROFILE_FULFILLED';
export const GET_PROFILE_REJECTED = 'GET_PROFILE_REJECTED';

export const UPDATE_PROFILE_PENDING = 'UPDATE_PROFILE_PENDING';
export const UPDATE_PROFILE_FULFILLED = 'UPDATE_PROFILE_FULFILLED';
export const UPDATE_PROFILE_REJECTED = 'UPDATE_PROFILE_REJECTED';

export const DELETE_PROFILE_PENDING = 'DELETE_PROFILE_PENDING';
export const DELETE_PROFILE_FULFILLED = 'DELETE_PROFILE_FULFILLED';
export const DELETE_PROFILE_REJECTED = 'DELETE_PROFILE_REJECTED';