export const GET_SEARCH_SUGGESTIONS_PENDING = 'GET_SEARCH_SUGGESTIONS_PENDING';
export const GET_SEARCH_SUGGESTIONS_FULFILLED = 'GET_SEARCH_SUGGESTIONS_FULFILLED';
export const GET_SEARCH_SUGGESTIONS_REJECTED = 'GET_SEARCH_SUGGESTIONS_REJECTED';

export const GET_SEARCH_HISTORY_PENDING = 'GET_SEARCH_HISTORY_PENDING';
export const GET_SEARCH_HISTORY_FULFILLED = 'GET_SEARCH_HISTORY_FULFILLED';
export const GET_SEARCH_HISTORY_REJECTED = 'GET_SEARCH_HISTORY_REJECTED';

export const GET_AUTOCOMPLETE_PENDING = 'GET_AUTOCOMPLETE_PENDING';
export const GET_AUTOCOMPLETE_FULFILLED = 'GET_AUTOCOMPLETE_FULFILLED';
export const GET_AUTOCOMPLETE_REJECTED = 'GET_AUTOCOMPLETE_REJECTED';

export const ADD_SEARCH_SUGGESTIONS_PENDING = 'ADD_SEARCH_SUGGESTIONS_PENDING';
export const ADD_SEARCH_SUGGESTIONS_FULFILLED = 'ADD_SEARCH_SUGGESTIONS_FULFILLED';
export const ADD_SEARCH_SUGGESTIONS_REJECTED = 'ADD_SEARCH_SUGGESTIONS_REJECTED';

export const REMOVE_SEARCH_SUGGESTIONS_PENDING = 'REMOVE_SEARCH_SUGGESTIONS_PENDING';
export const REMOVE_SEARCH_SUGGESTIONS_FULFILLED = 'REMOVE_SEARCH_SUGGESTIONS_FULFILLED';
export const REMOVE_SEARCH_SUGGESTIONS_REJECTED = 'REMOVE_SEARCH_SUGGESTIONS_REJECTED';

export const CLEAR_SEARCH_SUGGESTIONS_PENDING = 'CLEAR_SEARCH_SUGGESTIONS_PENDING';
export const CLEAR_SEARCH_SUGGESTIONS_FULFILLED = 'CLEAR_SEARCH_SUGGESTIONS_FULFILLED';
export const CLEAR_SEARCH_SUGGESTIONS_REJECTED = 'CLEAR_SEARCH_SUGGESTIONS_REJECTED';