export const GET_HOME_PRODUCTS_PENDING = 'GET_HOME_PRODUCTS_PENDING';
export const GET_HOME_PRODUCTS_FULFILLED = 'GET_HOME_PRODUCTS_FULFILLED';
export const GET_HOME_PRODUCTS_REJECTED = 'GET_HOME_PRODUCTS_REJECTED';