export const GET_REVIEWS_PENDING = 'GET_REVIEWS_PENDING';
export const GET_REVIEWS_FULFILLED = 'GET_REVIEWS_FULFILLED';
export const GET_REVIEWS_REJECTED = 'GET_REVIEWS_REJECTED';

export const ADD_REVIEW_PENDING = 'ADD_REVIEWS_PENDING';
export const ADD_REVIEW_FULFILLED = 'ADD_REVIEWS_FULFILLED';
export const ADD_REVIEW_REJECTED = 'ADD_REVIEWS_REJECTED';

export const UPDATE_REVIEW_PENDING = 'UPDATE_REVIEW_PENDING';
export const UPDATE_REVIEW_FULFILLED = 'UPDATE_REVIEW_FULFILLED';
export const UPDATE_REVIEW_REJECTED = 'UPDATE_REVIEW_REJECTED';

export const DELETE_REVIEW_PENDING = 'DELETE_REVIEW_PENDING';
export const DELETE_REVIEW_FULFILLED = 'DELETE_REVIEW_FULFILLED';
export const DELETE_REVIEW_REJECTED = 'DELETE_REVIEW_REJECTED';