export const GET_PRODUCT_FILTERS_PENDING = 'GET_PRODUCT_FILTERS_PENDING';
export const GET_PRODUCT_FILTERS_FULFILLED = 'GET_PRODUCT_FILTERS_FULFILLED';
export const GET_PRODUCT_FILTERS_REJECTED = 'GET_PRODUCT_FILTERS_REJECTED';