export const GET_PRODUCT_PENDING = 'GET_PRODUCT_PENDING';
export const GET_PRODUCT_FULFILLED = 'GET_PRODUCT_FULFILLED';
export const GET_PRODUCT_REJECTED = 'GET_PRODUCT_REJECTED';

export const GET_SIMILAR_PRODUCTS_PENDING = 'GET_SIMILAR_PRODUCTS_PENDING';
export const GET_SIMILAR_PRODUCTS_FULFILLED = 'GET_SIMILAR_PRODUCTS_FULFILLED';
export const GET_SIMILAR_PRODUCTS_REJECTED = 'GET_SIMILAR_PRODUCTS_REJECTED';

export const GET_LIKE_PRODUCTS_PENDING = 'GET_LIKE_PRODUCTS_PENDING';
export const GET_LIKE_PRODUCTS_FULFILLED = 'GET_LIKE_PRODUCTS_FULFILLED';
export const GET_LIKE_PRODUCTS_REJECTED = 'GET_LIKE_PRODUCTS_REJECTED';

export const UPDATE_PRODUCT_PENDING = 'UPDATE_PRODUCT_PENDING';
export const UPDATE_PRODUCT_FULFILLED = 'UPDATE_PRODUCT_FULFILLED';
export const UPDATE_PRODUCT_REJECTED = 'UPDATE_PRODUCT_REJECTED';

export const DELETE_PRODUCT_PENDING = 'DELETE_PRODUCT_PENDING';
export const DELETE_PRODUCT_FULFILLED = 'DELETE_PRODUCT_FULFILLED';
export const DELETE_PRODUCT_REJECTED = 'DELETE_PRODUCT_REJECTED';