export const GET_WISHLIST_PENDING = 'GET_WISHLIST_PENDING';
export const GET_WISHLIST_FULFILLED = 'GET_WISHLIST_FULFILLED';
export const GET_WISHLIST_REJECTED = 'GET_WISHLIST_REJECTED';

export const ADD_TO_WISHLIST_PENDING = 'ADD_TO_WISHLIST_PENDING';
export const ADD_TO_WISHLIST_FULFILLED = 'ADD_TO_WISHLIST_FULFILLED';
export const ADD_TO_WISHLIST_REJECTED = 'ADD_TO_WISHLIST_REJECTED';

export const REMOVE_FROM_WISHLIST_PENDING = 'REMOVE_FROM_WISHLIST_PENDING';
export const REMOVE_FROM_WISHLIST_FULFILLED = 'REMOVE_FROM_WISHLIST_FULFILLED';
export const REMOVE_FROM_WISHLIST_REJECTED = 'REMOVE_FROM_WISHLIST_REJECTED';