export const GET_SEARCHED_PRODUCTS_PENDING = 'GET_SEARCHED_PRODUCTS_PENDING';
export const GET_SEARCHED_PRODUCTS_FULFILLED = 'GET_SEARCHED_PRODUCTS_FULFILLED';
export const GET_SEARCHED_PRODUCTS_REJECTED = 'GET_SEARCHED_PRODUCTS_FULFILLED';

export const GET_PRODUCT_FILTERS_PENDING = 'GET_PRODUCT_FILTERS_PENDING';
export const GET_PRODUCT_FILTERS_FULFILLED = 'GET_PRODUCT_FILTERS_FULFILLED';
export const GET_PRODUCT_FILTERS_REJECTED = 'GET_PRODUCT_FILTERS_REJECTED';