export const GET_SEARCHED_PRODUCTS_PENDING = 'GET_SEARCHED_PRODUCTS_PENDING';
export const GET_SEARCHED_PRODUCTS_FULFILLED = 'GET_SEARCHED_PRODUCTS_FULFILLED';
export const GET_SEARCHED_PRODUCTS_REJECTED = 'GET_SEARCHED_PRODUCTS_REJECTED';