export const GET_CART_PENDING = 'GET_CART_PENDING';
export const GET_CART_FULFILLED = 'GET_CART_FULFILLED';
export const GET_CART_REJECTED = 'GET_CART_REJECTED';

export const ADD_TO_CART_PENDING = 'ADD_TO_CART_PENDING';
export const ADD_TO_CART_FULFILLED = 'ADD_TO_CART_FULFILLED';
export const ADD_TO_CART_REJECTED = 'ADD_TO_CART_REJECTED';

export const CLEAR_CART_PENDING = 'CLEAR_CART_PENDING';
export const CLEAR_CART_FULFILLED = 'CLEAR_CART_FULFILLED';
export const CLEAR_CART_REJECTED = 'CLEAR_CART_REJECTED';

export const UPDATE_CART_PENDING = 'UPDATE_CART_PENDING';
export const UPDATE_CART_FULFILLED = 'UPDATE_CART_FULFILLED';
export const UPDATE_CART_REJECTED = 'UPDATE_CART_REJECTED';

export const REMOVE_FROM_CART_PENDING = 'REMOVE_FROM_CART_PENDING';
export const REMOVE_FROM_CART_FULFILLED = 'REMOVE_FROM_CART_FULFILLED';
export const REMOVE_FROM_CART_REJECTED = 'REMOVE_FROM_CART_REJECTED';