export const GET_AUTOCOMPLETE_PENDING = 'GET_AUTOCOMPLETE_PENDING';
export const GET_AUTOCOMPLETE_FULFILLED = 'GET_AUTOCOMPLETE_FULFILLED';
export const GET_AUTOCOMPLETE_REJECTED = 'GET_AUTOCOMPLETE_REJECTED';